services:
  - type: web
    name: bundataanalysis
    runtime: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
